// SCREENS
export const SCREENS = {
  SPLASH: 'splashScreen',
  HOME: 'home',
  WEATHER_INFO: 'weatherInfo',
};

// CONSTANTS
export const SEARCH_HISTORY = 'SEARCH_HISTORY';
export const WEATHER_FETCH_START = 'WEATHER_FETCH_START';
export const WEATHER_FETCH_SUCCESS = 'WEATHER_FETCH_SUCCESS';
export const WEATHER_FETCH_ERROR = 'WEATHER_FETCH_ERROR';
